spring:
  application:
    name: engineplanning-service

feign:
  task-service:
    url: ${FEIGN_TASK_SERVICE_URL}
  profile-service:
    url: ${FEIGN_PROFILE_SERVICE_URL}

jwt:
  secret: ${JWT_SECRET}
