server:
  port: ${SERVER_PORT:1504}

spring:
  application:
    name: engineplanning-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

kafka:
  topics:
    notifications: planning.notifications

feign:
  task-service:
    url: ${FEIGN_TASK_SERVICE_URL}

  profile-service:
    url: ${FEIGN_PROFILE_SERVICE_URL}

  academic-service:
    url: ${FEIGN_ACADEMIC_SERVICE_URL}

  recommendation-service:
    url: ${FEIGN_RECOMMENDATION_SERVICE_URL}

jwt:
  secret: ${JWT_SECRET}

planning:
  priority:
    weight-proximity: 0.40
    weight-academic: 0.40
    weight-time: 0.20

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never

# ─── Logging ──────────────────────────────────────────────────────────────────
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{requestId:-no-req}] %-5level %logger{36} - %msg%n"
  level:
    com.aibert.dosw: INFO
    feign: WARN

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: qa
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  properties:
    security.protocol: SASL_SSL
    sasl.mechanism: PLAIN
    sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"${KAFKA_CONNECTION_STRING}\";"

---
spring:
  config:
    activate:
      on-profile: prod
