package com.aibert.dosw.domain.model.recommendation;

import com.aibert.dosw.domain.model.task.PlanningTask;
import java.time.LocalDate;
import java.util.List;
import lombok.Builder;
import lombok.Getter;

/**
 * Suggestion of what to study today (R19).
 * Combines the Java-calculated plan with the AI message
 * generated by Gemini or Groq.
 */
@Getter
@Builder
public class StudySuggestion {

    private final String userId;
    private final LocalDate date;

    /** Tasks ordered by priority for today. */
    private final List<PlanningTask> suggestedTasks;

    /** Suggested hours per task. */
    private final List<Double> hoursPerTask;

    /** Motivational message generated by the AI. */
    private final String aiMessage;

    /** List of specific recommendations. */
    private final List<Recommendation> recommendations;

    /** Indicates whether the message was generated by AI or Java rules. */
    private final boolean generatedByAi;

    /**
     * Total suggested study hours for today.
     */
    public double getTotalSuggestedHours() {
        if (hoursPerTask == null)
            return 0.0;
        return hoursPerTask.stream()
                .mapToDouble(Double::doubleValue)
                .sum();
    }

    /**
     * Checks whether there are critical tasks today.
     */
    public boolean hasCriticalTasks() {
        if (suggestedTasks == null)
            return false;
        return suggestedTasks.stream()
                .anyMatch(PlanningTask::isHighPriority);
    }
}
