package com.aibert.dosw.domain.model.schedule;

import com.aibert.dosw.domain.model.task.PlanningTask;
import java.util.List;
import lombok.Builder;
import lombok.Getter;

/**
 * Represents the complete weekly distribution plan generated by the engine.
 * Contains both the successfully assigned time blocks and tasks that couldn't
 * fit.
 */
@Getter
@Builder
public class WeeklyDistributionPlan {
    private final String studentId;
    private final List<ScheduledBlock> assignedBlocks;
    private final List<PlanningTask> unassignedTasks;

    /**
     * Checks if the distribution was 100% successful (all tasks fitted).
     */
    public boolean isFullyAssigned() {
        return unassignedTasks == null || unassignedTasks.isEmpty();
    }

    /**
     * Returns a distinct list of all tasks that are currently marked as CRITICAL.
     */
    public List<PlanningTask> getCriticalTasks() {
        List<PlanningTask> criticals = new java.util.ArrayList<>();
        if (assignedBlocks != null) {
            assignedBlocks.stream()
                    .map(ScheduledBlock::getTask)
                    .filter(t -> t.getPriorityLevel() == com.aibert.dosw.domain.model.task.TaskPriority.CRITICAL)
                    .forEach(criticals::add);
        }
        if (unassignedTasks != null) {
            unassignedTasks.stream()
                    .filter(t -> t.getPriorityLevel() == com.aibert.dosw.domain.model.task.TaskPriority.CRITICAL)
                    .forEach(criticals::add);
        }
        return criticals.stream().distinct().toList();
    }
}
