package com.aibert.dosw.domain.model.schedule;

import com.aibert.dosw.domain.model.context.MovedTaskRecord;
import com.aibert.dosw.domain.model.context.OverloadedDayRecord;
import com.aibert.dosw.domain.model.task.PlanningTask;
import com.aibert.dosw.domain.model.task.TaskPriority;
import java.util.ArrayList;
import java.util.List;
import lombok.Builder;
import lombok.Getter;
import lombok.Singular;

/**
 * Represents the complete weekly distribution plan generated by the engine.
 * Contains both the successfully assigned time blocks and tasks that couldn't
 * fit.
 */
@Getter
@Builder
public class WeeklyDistributionPlan {
    private final String studentId;
    private final List<ScheduledBlock> assignedBlocks;
    private final List<PlanningTask> unassignedTasks;

    /**
     * Tasks that were relocated during a rebalancing operation (R17).
     * Each record contains the original block and new block assigned.
     */
    @Singular("movedTask")
    private final List<MovedTaskRecord> movedTasks;

    /**
     * AIB-27: Days where the proposed plan (without the cap) would have exceeded
     * MAX_MINUTES_PER_DAY = 240. Empty when no overload was detected.
     */
    private final List<OverloadedDayRecord> overloadedDays;

    /**
     * AIB-25 / AIB-26 / AIB-27 — Optional override message.
     * Set when a specific FA scenario is detected or overload protection is
     * applied.
     * When non-null, the mapper uses this value instead of the default message.
     */
    private final String message;

    /**
     * Checks if the distribution was 100% successful (all tasks fitted).
     */
    public boolean isFullyAssigned() {
        return unassignedTasks == null || unassignedTasks.isEmpty();
    }

    /**
     * Returns a distinct list of all tasks that are currently marked as CRITICAL
     * (deadline <24h).
     * Used for the criticalAlerts field in the response (R17 RN-02).
     */
    public List<PlanningTask> getCriticalTasks() {
        List<PlanningTask> criticals = new ArrayList<>();
        if (assignedBlocks != null) {
            assignedBlocks.stream()
                    .map(ScheduledBlock::getTask)
                    .filter(t -> t.getPriorityLevel() == TaskPriority.CRITICAL)
                    .forEach(criticals::add);
        }
        if (unassignedTasks != null) {
            unassignedTasks.stream()
                    .filter(t -> t.getPriorityLevel() == TaskPriority.CRITICAL)
                    .forEach(criticals::add);
        }
        return criticals.stream().distinct().toList();
    }
}
